[versions]
 appcompat = "1.7.1"
core = "1.7.0"
coreKtx = "1.17.0"
junit = "4.13.2"
kotlinxSerializationJson = "1.9.0"
lifecycleRuntimeKtx = "2.9.4"
mobilisten = "7.0.0"
mockito = "5.20.0"
mockitoKotlin = "6.1.0"
mockk = "1.14.6"
robolectric = "4.16"

[libraries]

appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
core = { module = "androidx.test:core", version.ref = "core" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleRuntimeKtx" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
mobilisten = { module = "com.zoho.salesiq:mobilisten", version.ref = "mobilisten" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
