name: Release SDK

on:
  push:
    branches:
      - main
    paths:
      - android/**
      - ios/**

jobs:
  build-and-release-android:
    name: Build and Release Android SDK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch || github.ref }}
          fetch-depth: 0

      - name: Verify version detection
        run: |
          echo "Verifying git tag detection..."
          git describe --tags --abbrev=0
          echo "Expected version: ${{ github.event.inputs.version }}"

      - name: Build Android SDK
        working-directory: android
        run: |
          chmod +x gradlew
          ./gradlew :lyrazohoandroid:assembleRelease

      - name: Publish Android SDK
        working-directory: android
        env:
          GPR_KEY: ${{ secrets.GITHUB_TOKEN }}
          GPR_USER: ${{ secrets.actor }}
        run: |
          chmod +x gradlew
          ./gradlew :lyrazohoandroid:publishReleasePublicationToGitHubPackagesRepository
