name: Release SDK

on:
  push:
    tags:
      - "*"
    paths-ignore:
      - .github/**

jobs:
  build-and-release-android:
    name: Build and Release Android SDK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Build Android SDK
        working-directory: android
        run: |
          chmod +x gradlew
          ./gradlew :lyrazohoandroid:assembleRelease

      - name: Publish Android SDK
        working-directory: android
        env:
          GPR_KEY: ${{ secrets.GITHUB_TOKEN }}
          GPR_USER: ${{ secrets.actor }}
        run: |
          chmod +x gradlew
          ./gradlew :lyrazohoandroid:publishReleasePublicationToGitHubPackagesRepository
